using System.Collections.Generic;

namespace ProjectEuler
{
    internal class Program
    {
        static void Main()
        {
            Console.WriteLine();
        }

        #region 1

        /*
            If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
            Find the sum of all the multiples of 3 or 5 below 1000.
        */

        static int GetEvenNumbersFromFibonacciSequence(int number)
        {
            int result = 0;

            int firstNumber = 1;
            int secondNumber = 2;

            int temp;

            while (secondNumber < number)
            {
                if (secondNumber % 2 == 0)
                    result += secondNumber;

                temp = secondNumber;
                secondNumber = firstNumber + secondNumber;
                firstNumber = temp;
            }

            return result;
        }
        #endregion

        #region 2

        /*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        */

        static int CountSumOfMultiples(int destinationNumber, params int[] multiples)
        {
            int result = 0;
            int multiplesLength = multiples.Length;
            int j = 0;

            for (int i = 1; i < destinationNumber; ++i)
            {
                for (; j < multiplesLength; ++j)
                {
                    if (i % multiples[j] == 0)
                    {
                        result += i;
                        break;
                    }
                }

                j = 0;
            }

            return result;
        }
        #endregion
    }
}